name: Shinyapps IO Deployment
run-name: ${{ github.actor }} Deployment of Backend

on:
  push: # Push to main on backend_py folder triggers this workflow
    branches:
      - 'main'
    paths:
      - 'backend_py/**'
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.x'

      - name: Install rsconnect for Python
        run: pip install rsconnect-python

      - name: Add rsconnect account
        env:
            RSCONNECT_ACCOUNT: ${{ secrets.RSCONNECT_ACCOUNT }}
            RSCONNECT_NAME: ${{ secrets.RSCONNECT_NAME }}
            RSCONNECT_TOKEN: ${{ secrets.RSCONNECT_TOKEN }}
            RSCONNECT_SECRET: ${{ secrets.RSCONNECT_SECRET }}
            RSCONNECT_APP_ID: ${{ secrets.RSCONNECT_APP_ID }}
        run: |
            rsconnect add \
              --account $RSCONNECT_ACCOUNT \
              --name $RSCONNECT_NAME \
              --token $RSCONNECT_TOKEN \
              --secret $RSCONNECT_SECRET
    
      - name: Debug App ID
        run: |
          echo "App ID: $RSCONNECT_APP_ID"
        
      - name: Deploy Shiny app
        run: |
          echo "App ID: $RSCONNECT_APP_ID"
          echo "Deploying from $GITHUB_WORKSPACE/backend_py"
          rsconnect deploy shiny "$GITHUB_WORKSPACE/backend_py" \
            --name "$RSCONNECT_NAME" \
            --title "aquawatchmobilepy" \
            --app-id "$RSCONNECT_APP_ID" \
            --mode python-shiny
