name: Shinyapps IO Deployment
run-name: ${{ github.actor }} Deployment of Backend

on:
  push: # Push to main on backend_py folder triggers this workflow
    branches:
      - 'main'
    paths:
      - 'backend_py/**'
    paths-ignore:
      - 'README.md'
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.x'

      - name: Install rsconnect for Python
        run: pip install rsconnect-python

      - name: Install project dependencies
        run: |
          if [ -f "backend_py/requirements.txt" ]; then 
            pip install -r backend_py/requirements.txt
          fi

      - name: Add rsconnect account
        env:
            RSCONNECT_ACCOUNT: ${{ secrets.RSCONNECT_ACCOUNT }}
            RSCONNECT_NAME: ${{ secrets.RSCONNECT_NAME }}
            RSCONNECT_TOKEN: ${{ secrets.RSCONNECT_TOKEN }}
            RSCONNECT_SECRET: ${{ secrets.RSCONNECT_SECRET }}
        run: |
            rsconnect add \
              --account $RSCONNECT_ACCOUNT \
              --name $RSCONNECT_NAME \
              --token $RSCONNECT_TOKEN \
              --secret $RSCONNECT_SECRET

        # Deploy the Shiny app
      - name: Deploy Shiny app
        run: |
            rsconnect deploy shiny backend_py \
              --name $RSCONNECT_NAME \
              --title "aquawatchmobile"
